CREATE TABLE marks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    longitude DOUBLE NOT NULL,
    latitude DOUBLE NOT NULL,
    accuracy DOUBLE NOT NULL,
    time_added TIMESTAMP NOT NULL,
    road_type VARCHAR(32) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    status VARCHAR(16) DEFAULT 'ACTIVE'
);